application: woodersonbot
version: 1
runtime: python27
threadsafe: true
api_version: 1

builtins:
- appstats: on
- datastore_admin: on
- deferred: on
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /cron/.*
  script: main.private_app
  login: admin

- url: .*
  script: main.public_app
