application: woodersonbot
version: 1
runtime: python27
threadsafe: true
api_version: 1

builtins:
- appstats: on
- datastore_admin: on
- deferred: on
- remote_api: on

handlers:
- url: /(favicon\.ico|robots\.txt)
  static_files: static/$1
  upload: static/$1

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /cron/.*
  script: main.app
  login: admin
